version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    expose:
      - '3306'
    environment:
       MYSQL_DATABASE: 'stripePayments'
       # So you don't have to use root, but you can if you like
       MYSQL_USER: 'paymentUser'
       # You can use whatever password you like
       MYSQL_PASSWORD: 'P4ym3nt'
       # Password for root access
       MYSQL_ROOT_PASSWORD: 'P4ym3nt'
    container_name: mySQLPaymentDB
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: